import { createElement } from 'lwc'; //instantiate the componnet we want to tset
import StudentBrowser from 'c/studentBrowser'; //import the component you want to test

describe('c-student-browser', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild); //clean up the cokmpoenent after each test
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {  //test block  
        // Arrange
        const element = createElement('c-student-browser', {
            is: StudentBrowser
        });

        // Act
        document.body.appendChild(element); //add the element to DOM for testing....

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);  // Expected value  vs actual value
    });
});

//Watch mode checks the code as soon as we do any change on it
